micronaut:
  application:
    name: fretesRest

#configurando channel grpc
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    fretes:
      addres: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10